sysTenantId: '000000'
sysUsername: admin
sysPassword: wimi123456,
scheme: https
host: alpha.masterlink.cloud:443
headers:
  Content-Type: application/json
  Authorization: Basic c2FiZXI6c2FiZXJfc2VjcmV0
  Blade-Auth: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJlYWxfbmFtZSI6IueuoeeQhuWRmCIsImF2YXRhciI6Imh0dHBzOi8vY3BzMjAyMC5vYnMuY24tZWFzdC0yLm15aHVhd2VpY2xvdWQuY29tL3VwbG9hZC8yMDIxMDkxNS84Yjc0ZDliZmNlYjhmMjk0M2M4NDYzYjBmNDViNWMxZS5qcGciLCJhdXRob3JpdGllcyI6WyJhZG1pbmlzdHJhdG9yIl0sImNsaWVudF9pZCI6InNhYmVyIiwicm9sZV9uYW1lIjoiYWRtaW5pc3RyYXRvciIsInBvc3RfaWQiOiIxMTIzNTk4ODE3NzM4Njc1MjAxIiwidXNlcl9pZCI6IjExMjM1OTg4MjE3Mzg2NzUyMDEiLCJyb2xlX2lkIjoiMTEyMzU5ODgxNjczODY3NTIwMSIsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiLnrqHnkIblkZgiLCJvYXV0aF9pZCI6IiIsImV4cCI6MTYzNTA5MDExOCwiZGVwdF9pZCI6IjExMjM1OTg4MTM3Mzg2NzUyMDEiLCJqdGkiOiIxZTgwMDVhMC02ZDUzLTQ0YjktYTcyNS1lOGY2ZTBlYzY5NTciLCJhY2NvdW50IjoiYWRtaW4iLCJ0ZW5hbnRfY2xhc3NlcyI6MX0.dQhtdu5ObxtolEnW6QW3J0WEiuXM_gzWrbKDmnUuPS8
