# 运行项目名
project_name: masterlink

# 运行模式:
auto_switch: 0
# 0 -不开启自动生成测试用例功能，将直接运行测试
# 1 -根据手工编写用例，自动生成测试脚本，然后运行测试
# 2 -根据接口抓包数据，自动生成测试用例和测试脚本，然后运行测试
# 3 -根据接口抓包数据，自动生成测试用例和测试脚本，但不运行测试
# 注意：目前解析仅支持(.chlsj)格式，请使用Charles工具抓包导出JSON Session File

# 扫描测试用例目录（且仅当auto_switch=1时有用）
scan_dir:

# 使用模糊匹配测试用例（空则匹配所有）
pattern:

# 执行并发线程数（0表示不开启）
process: 0

# 失败重试次数（0表示不重试）
reruns: 0

# 本轮测试最大允许失败数（超出则立即结束测试）
maxfail: 20

# 接口调用间隔时间（s）
interval: 1

# 测试结果校验方式说明（共5种方式）：
# no_check：不做任何校验
# check_code：仅校验接口返回码code
# check_json：校验接口返回码code，并进行json格式比较返回结果（默认方式）
# entirely_check：校验接口返回码code，并进行完整比较返回结果
# regular_check：校验接口返回码code，并进行正则匹配返回结果